<?php

namespace App\Services\Billing;

use App\Contracts\Billing\BillingGateway;
use App\Exceptions\BillingUnavailableException;
use App\Models\User;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use Throwable;

class PolarBillingGateway implements BillingGateway
{
    public function providerCode(): string
    {
        return 'polar';
    }

    public function configured(): bool
    {
        $token = trim(
            (string) config(
                'billing.polar.access_token',
                ''
            )
        );

        $environment = strtolower(
            trim(
                (string) config(
                    'billing.polar.environment',
                    'production'
                )
            )
        );

        $professionalProduct = trim(
            (string) config(
                'billing.polar.products.professional',
                ''
            )
        );

        $teamProduct = trim(
            (string) config(
                'billing.polar.products.team',
                ''
            )
        );

        return (
            $token !== ''
            && in_array(
                $environment,
                ['sandbox', 'production'],
                true
            )
            && $this->validUuid($professionalProduct)
            && $this->validUuid($teamProduct)
        );
    }

    public function createCheckout(
        User $user,
        string $planCode,
    ): array {
        if (! $this->configured()) {
            throw new BillingUnavailableException(
                'Polar billing is not fully configured.'
            );
        }

        $productId = trim(
            (string) config(
                "billing.polar.products.{$planCode}",
                ''
            )
        );

        if (! $this->validUuid($productId)) {
            throw new BillingUnavailableException(
                'The selected Polar product is not configured.'
            );
        }

        $token = trim(
            (string) config(
                'billing.polar.access_token',
                ''
            )
        );

        try {
            $response = Http::acceptJson()
                ->asJson()
                ->withToken($token)
                ->timeout(20)
                ->post(
                    $this->apiBaseUrl() . '/v1/checkouts/',
                    [
                        'product_id' => $productId,

                        /*
                         * Metadata is generated by the authenticated
                         * CrypticX backend, never trusted from browser
                         * input. It will later bind the Polar
                         * subscription to the CrypticX user and plan.
                         */
                        'metadata' => [
                            'user_id' => (string) $user->id,
                            'plan_code' => $planCode,
                        ],

                        'success_url' =>
                            rtrim(
                                (string) config(
                                    'billing.frontend_url'
                                ),
                                '/'
                            )
                            . '/profile?billing=success',
                    ],
                );
        } catch (ConnectionException) {
            throw new BillingUnavailableException(
                'Unable to reach Polar billing.'
            );
        } catch (Throwable) {
            throw new BillingUnavailableException(
                'Polar checkout could not be created.'
            );
        }

        if (! $response->successful()) {
            throw new BillingUnavailableException(
                'Polar rejected the checkout request.'
            );
        }

        $checkoutId = trim(
            (string) $response->json('id', '')
        );

        $checkoutUrl = trim(
            (string) $response->json('url', '')
        );

        if (
            ! $this->validUuid($checkoutId)
            || ! filter_var(
                $checkoutUrl,
                FILTER_VALIDATE_URL
            )
        ) {
            throw new BillingUnavailableException(
                'Polar returned an invalid checkout session.'
            );
        }

        return [
            'transaction_id' => $checkoutId,
            'provider' => 'polar',
            'checkout_url' => $checkoutUrl,
        ];
    }

    private function apiBaseUrl(): string
    {
        $environment = strtolower(
            trim(
                (string) config(
                    'billing.polar.environment',
                    'production'
                )
            )
        );

        return $environment === 'sandbox'
            ? 'https://sandbox-api.polar.sh'
            : 'https://api.polar.sh';
    }

    private function validUuid(
        string $value,
    ): bool {
        return (bool) preg_match(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',
            $value
        );
    }
}
